---
driver_plugin: vagrant
driver_config:
  require_chef_omnibus: true

platforms:
  - name: debian-7.2
    driver_config:
      box: opscode_debian-7.2.0_chef-provisionerless.box
      box_url: https://opscode-vm-bento.s3.amazonaws.com/vagrant/virtualbox/opscode_debian-7.2.0_chef-provisionerless.box

suites:
- name: beef
  run_list:
  - recipe[beef]
  attributes: {
    beef: {
      path: '/home/beef/beefproject',
      user: 'beef',
      user_home: '/home/beef',
      ruby_version: '1.9.3-p547'
    }
  }
