---
driver:
  name: docker
  binary: docker
  use_sudo: false

provisioner:
  name: chef_zero

platforms:
  - name: debian-7
    run_list:
      - recipe[apt]
  - name: debian-8
    run_list:
      - recipe[apt]

suites:
- name: beef
  run_list:
  - recipe[beef]
  - recipe[beef::service]
  attributes:
    beef:
      user: 'beef'
      path: '/home/beef'
      service:
        NAME: beef-test
