---
driver_plugin: vagrant
driver_config:
  require_chef_omnibus: true

platforms:
- name: debian-7.6
  run_list:
  - recipe[apt]

suites:
- name: beef
  run_list:
  - recipe[beef]
  attributes:
    beef:
      user: 'beef'
      path: '/home/beef'
